language: node_js
node_js:
  - "14"
before_script:
  - cd 06-ionic/ionicTest2
  - npm install
script: npm run build
deploy:
  local-dir: 06-ionic/ionicTest2/www
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
notifications:
  email: false