language: node_js
node_js:
- "14"
before_script:
- cd repertoire_projet
- npm install
script: npm run build
deploy:
local-dir: repertoire_projet/www
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
on:
branch: main
notifications:
email: false